name: Application Testing
on: [push, pull_request]

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Vue application
        run: |
          cd resources/frontend
          npm ci
          npm run build
          rm -rf node_modules
